### ISSUE TITLE
Can't load Entities with Entity attributes

### ISSUE THREAD

**Issue by nmobregon** [artifacthealth/hydrate-mongodb#2]
When trying to load entities with attributes that represent other entities I always get an error when trying to stringify.

Here is my code

```
@Entity()
export class User {
    @Id()
    _id: string;
    @Field()
    email: string;
    @Field()
    password:string;
}

@Entity()
export class Prueba {
    
    @Id()
    _id:string;
    
    @Field()
    name:string;
    
}


@Entity()
export class Solicitud {
    
    @Id()
    _id: string;
    
    @Field()
    paciente:string;
    
    @Field()
    edad:number;
    
    @Enumerated(Genero)
    genero:Genero;
    
    @Enumerated(Raza)
    raza:Raza;
    
    @Enumerated(Modulo)
    modulo:Modulo;
    
    @Type("User")
    user:User;

    @Type("Prueba")
    user:Prueba;
}
```
I can save ok, but when I find all, this is what I get when I console.log each attribute of the entity and its type (   `console.log(attr, typeof attr); `  ) and after that, when express tries to stringify the entity within the Response as json, it throws an exception
```

57436f7bd0da256b65e577c3 'object'
Ernesto string
23 'number'
1 'number'
3 'number'
0 'number'
Reference {
  mapping: 
   EntityMapping {
     flags: 5188,
     id: 12,
     properties: [ [Object], [Object], [Object] ],
     _propertiesByName: 
      Map {
        '_id' => [Object],
        'email' => [Object],
        'password' => [Object] },
     _propertiesByField: 
      Map {
        '_id' => [Object],
        'email' => [Object],
        'password' => [Object] },
     _baseClass: undefined,
     inheritanceRoot: [Circular],
     name: 'User',
     classConstructor: [Function: User],
     _lifecycleCallbacksAsync: [ [Object] ],
     discriminatorField: '__t',
     versioned: true,
     versionField: '__v',
     changeTracking: 2,
     collectionName: 'user',
     identity: ObjectIdGenerator {},
     setQueryDocumentDiscriminator: [Function],
     getDocumentDiscriminator: [Function],
     _resolveCache: Map { 'email' => [Object] },
     _registry: MappingRegistry { _mappings: [Object] } },
  _id: 573f5487f2df27362e3ca0f5 } 'object'
uploads/db251a4ccba831e4dc9e1f7d6d39e9de string
uploads/0ee7f93ab9666f9f131f16262dc807ee string
Reference {
  mapping: 
   EntityMapping {
     flags: 5188,
     id: 7,
     properties: [ [Object], [Object] ],
     _propertiesByName: Map { '_id' => [Object], 'name' => [Object] },
     _propertiesByField: Map { '_id' => [Object], 'name' => [Object] },
     _baseClass: undefined,
     inheritanceRoot: [Circular],
     name: 'Prueba',
     classConstructor: [Function: Prueba],
     discriminatorField: '__t',
     versioned: true,
     versionField: '__v',
     changeTracking: 2,
     collectionName: 'prueba',
     identity: ObjectIdGenerator {},
     _registry: MappingRegistry { _mappings: [Object] },
     setDocumentDiscriminator: [Function],
     setDocumentVersion: [Function] },
  _id: 57436f7bd0da256b65e577c2 } 'object'
[Function: SolicitudModulo1] 'function'
/home/nmobregon/Applications/glovasc-wksp/glovasc/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
 
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.json (/home/myapp/node_modules/express/lib/response.js:242:19)
    at Object.callback (/home/myapp/dist/src/controller/SolicitudController.js:66:26)
    at /home/myapp/node_modules/hydrate-mongodb/taskQueue.js:91:22
    at /home/myapp/node_modules/hydrate-mongodb/persister.js:195:28
    at handleCallback (/home/myapp/node_modules/mongodb/lib/utils.js:96:12)
    at /home/myapp/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/home/myapp/node_modules/mongodb-core/lib/cursor.js:159:5)
    at setCursorDeadAndNotified (/home/myapp/node_modules/mongodb-core/lib/cursor.js:501:3)
    at nextFunction (/home/myapp/node_modules/mongodb-core/lib/cursor.js:652:7)
```

Any ideas about this?

**Comment by meirgottlieb** [comment]
A few things:

1. You shouldn't be using the @Id decorator on the _id property. The _id property is reserved for the internal MongoDB identifier. The @Id decorator is used to represent the identifier as a string. Try using a property named "id" without the underscore. For example:
```
@Entity()
export class User {
    @Id()
    id: string;
```
2. You can't reliably call JSON.stringify on hydrated entities. They can represent complex object graphs while JSON must a simple tree structure. FYI, the Reference with the mapping is an un-fetched reference to a User object. The Reference includes the mapping and the identifier for the un-fetched reference. You definitely don't want to be sending that to the client.

**Comment by meirgottlieb** [comment]
@nmobregon, I added a new method to the session [toDocument](https://artifacthealth.github.io/hydrate-mongodb/interfaces/session.html#todocument) that allows you to serialize an entity to a document. The document is the same thing that is stored in MongoDB and is suitable for serialization to JSON. 

For example:
```
console.log(JSON.stringify(session.toDocument(user)));
```
