### ISSUE TITLE
Problems with : findOneAndRemove 

### ISSUE THREAD

**Issue by robgrimball** [artifacthealth/hydrate-mongodb#26]
This is probably something I am doing wrong, but I can't figure out what it is, so it may also just be a bug.  I am using v1.9.0 of hydrate-mongodb.

I am trying to use findOneAndRemove to find an entity by its id, delete it, and return the entity that was deleted.  Below is the code fragment in question.  It does in fact delete the entity from the database, but then throws an error which will follow as well.

```
        const session = this.sessionFactory.createSession();

        session.query(Permissions).findOneAndRemove({
            _id: new ObjectID(id),
        }).execute((err, permission) => {
            session.close(() => {
                showDeleted(permission);
            });
        });
```
Here is the error I am getting: 

```

/home/node_modules/hydrate-mongodb/persister.js:550
                        self._session.notifyRemoved(entity);
                            ^
TypeError: Cannot read property '_session' of undefined
    at handleCallback (/home/node_modules/hydrate-mongodb/persister.js:550:29)
    at /home/node_modules/hydrate-mongodb/persister.js:537:21
    at PersisterImpl._loadOne (/home/node_modules/hydrate-mongodb/persister.js:692:21)
    at /home/node_modules/hydrate-mongodb/persister.js:533:23
    at handleCallback (/home/node_modules/mongodb/lib/utils.js:120:56)
    at /home/node_modules/mongodb/lib/collection.js:2494:14
    at handleCallback (/home/node_modules/mongodb/lib/utils.js:120:56)
    at /home/node_modules/mongodb/lib/db.js:315:5
    at /home/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
```

Any help with this is appreciated.

Thanks

**Comment by meirgottlieb** [comment]
This was a bug. Thank you for reporting it. I just posted a fix to NPM, version 1.9.2. Also, you can make that call more concise: 1) You don't need to convert the string id to an ObjectID, Hydrate will do that for you, and 2) You can use the callback instead of `execute`:

```
 const session = this.sessionFactory.createSession();

        session.query(Permissions).findOneAndRemove({ _id: id }, (err, permission) => {
            session.close(() => {
                showDeleted(permission);
            });
        });
```
